### PR TITLE
Partly fix a bug in calculateDeterministicBonus()

### PR DESCRIPTION
**Pull request by mrguenther**
This is a stop-gap fix that addresses the most likely failure modes.

Bug: kgar/foundry-vtt-tidy-5e-sheets#667

### CODE REVIEW

**Comment by kgar** [comment]
I'll take a closer look at this tomorrow. Thank you for taking the time to sort this out!

**Comment by kgar** [comment]
@mrguenther check my commit and let me know if that works for you. I made changes to pass the check, and I extended the try/catch to the roll as well, because as it turns out, a successfully validated roll can still error out :C

**Comment by kgar** [comment]
I'm going to go ahead with what we have here and cut another dnd5e 3.2.x release. Tidy V5 for dnd5e 3.3.0 will go out shortly after.

Thanks again for diagnosing and providing this fix. I hope we can come back to it in the future and refine it further.

**Review by kgar — APPROVED** [review]

**Comment by mrguenther** [comment]
Sorry, I thought I'd responded a while ago. Yes, the fix worked.

**Pull request merged**
