### PR TITLE
Add module compatibility with lazymoney

### PR DESCRIPTION
**Pull request by p4535992**
i have tried on my side the code: https://github.com/p4535992/foundryvtt-lazymoney-dnd5e/blob/3d04fd2fcc19c72206303ce71083811f0c43ecf4/src/scripts/main.js#L41

but i cannot retrieve the `event.target.value` in any way so i have tried to add the solution on your side .

First time with svelte so i probably do something stupid.

### CODE REVIEW

**Comment by kgar** [comment]
I could add a pre-update hook for currency that could help with this.

How about this approach?
```js
Hooks.on('tidy5e-sheet.preUpdateCurrency', (app, currencyUpdate) => {
  const document = app.document; // can tell if Character, NPC, Vehicle, Container by `app.document.type`
  const { value, denomination } = currencyUpdate;

  // ... code to take over currency changes

  return false; // Prevent the update from firing on Tidy side.
});
```

This would provide a nice hook for any other currency-affecting modules in the future.

**Comment by kgar** [comment]
But actually, there's an even better option.

Core Foundry has the `preUpdateActor` hook where you can change the result of an update:
```js
Hooks.on('preUpdateActor', (actor, update, ...rest) => {
    if (update?.system?.currency) {
        Object.entries(update?.system?.currency).forEach(([key, value]) => update.system.currency[key] = (value ?? 0) * 2);
        console.warn("I changed the money! Bahahahahaha!");
       // Replace my DOUBLE MONEY cheat with lazy money logic.
    }
})
```

Would this option work for you? I tested it locally, and it affected any sheet that I updated, whether Tidy or new default or otherwise.

**Comment by kgar** [comment]
With containers being an additional source for currency outside of actors, the `preUpdateItem` hook also works the same:

```js
Hooks.on('preUpdateItem', (actor, update, ...rest) => {
    if (update?.system?.currency) {
        Object.entries(update?.system?.currency).forEach(([key, value]) => update.system.currency[key] = (value ?? 0) * 2);
        console.warn("I changed the money! Bahahahahaha!");
       // swap this logic for lazy money magic
    }
})
```

**Comment by p4535992** [comment]
All of these solutions are more than fine for my use case choose the one that suits you best

**Comment by p4535992** [comment]
> But actually, there's an even better option.
> 
> Core Foundry has the `preUpdateActor` hook where you can change the result of an update:
> 
> ```js
> Hooks.on('preUpdateActor', (actor, update, ...rest) => {
>     if (update?.system?.currency) {
>         Object.entries(update?.system?.currency).forEach(([key, value]) => update.system.currency[key] = (value ?? 0) * 2);
>         console.warn("I changed the money! Bahahahahaha!");
>        // Replace my DOUBLE MONEY cheat with lazy money logic.
>     }
> })
> ```
> 
> Would this option work for you? I tested it locally, and it affected any sheet that I updated, whether Tidy or new default or otherwise.

That's is actually a good suggestion...

**Comment by p4535992** [comment]
Nothing to much problems with others modules using the hooks. i tried the following code, but the `preUpdateActor`, but it seem to not work well with other modules, and also pass to me the number no the string.

```
Hooks.on("preUpdateActor", (actor, update, ...rest) => {
    if (!game.settings.get(CONSTANTS.MODULE_ID, "enable")) {
        return;
    }
    if (game.system.id === "dnd5e") {
        const currency = foundry.utils.getProperty(update, API.ACTOR_CURRENCY_ATTRIBUTE) || undefined;
        if (currency) {
            const currencyActor = foundry.utils.getProperty(actor, API.ACTOR_CURRENCY_ATTRIBUTE) || {};
            Object.entries(currency).forEach(([key, value]) => {
               // Also i must do this because the update object has number not string
                const currencyData = foundry.utils.getProperty(currency, key);
                const currencyActorData = foundry.utils.getProperty(currencyActor, key);
                let currencyDataS = String(currencyData);
                if(currencyData < currencyActorData) {
                    currencyDataS = "-"+(currencyActorData-currencyData);
                }
                else if(currencyData > currencyActorData) {
                    currencyDataS = "+"+(currencyData-currencyActorData);
                }
                else if(currencyData === currencyActorData) {
                    currencyDataS = "="+(currencyData);
                }
                LazyMoneyHelpers.manageCurrencySync(actor, currencyDataS, key);
            });
            foundry.utils.setProperty(update, API.ACTOR_CURRENCY_ATTRIBUTE, undefined);
        }
    } 
    else {
        Logger.warn(`The system '${game.system.id }' is not supported open a issue on the project`, false);
    }
    // TODO ADD OTHER SYSTEM
});
```

the best solution is some html selector i can use on the tidysheet5e like i'm doing on the standard one with this code:
```
export function applyLazyMoney(app, html, actorData, itemSelector) {
    if (!game.settings.get(CONSTANTS.MODULE_ID, "enable")) {
        return;
    }
    html.find(itemSelector).off("change"); // Stop default sheet behaviour 
    html.find(itemSelector).change(
        {
            app: app,
            data: actorData,
        },
        _onChangeCurrency, // my code
    );
}

function _onChangeCurrency(ev) {
    const input = ev.target;
    const actor = ev.data.app.actor;
    const sheet = ev.data.app.options;
    const denom = input.name.split(".")[2];
    const value = input.value;
   // DO SOMETHING
}
```

**Pull request closed without merging**
